---
output:
  pdf_document:
    includes:
      in_header: "~/headRs/StatHead.sty"
fontsize: 11pt
bibliography: "../../causal.bib"
# csl: "`r path.expand('~/HeadRs/csl/ama.csl')`"
---

# Introduction

The United Auto Workers-General Motors (UAW-GM) Cohort Study is a longitudinal occupational cohort study established in the early 1980s to study the health effects of metalworking fluids [@Eisen_1992;@Eisen_2001]. Metalworking fluids (MWF) are complex mixtures of fluids used in industrial metalworking operations to lubricate and cool machinery and parts. The three major classes of MWF are straight, soluble, and synthetic metalworking fluids [@Byers_2006]. Possible routes of human exposure include absorption through skin, inhalation of aerosols, and ingestion of droplets.

A central concern in the analysis of longitudinal occupational cohort data is the potential for bias due to the healthy worker survivor effect (HWSE), the phenomenon by which healthy individuals remain at work, while less healthy individuals leave work -- possibly in response to exposure-related health decline. In the presence of the HWSE, those with the highest cumulative occupational exposures are also those who are less at risk of disease (more likely to have potential outcome no disease under both exposure and no exposure scenarios). Thus, standard measures of association would show an inverse relationship between occupational exposure and poor health outcomes [@Arrighi_1994]. The HWSE is an example of time-varying confounding affected by past exposure. Previous studies have attempted to assess the presence of the HWSE in observed data by assessing so-called path-specific associations using Cox proportional hazards modeling [@Naimi_2013;@Garcia_2017]. However, in those studies, the estimates were themselves subject to the confounding structures they sought to characterize.

If conditional sequential ignorability of exposure and censoring status at each point in follow-up and positivity (overlap) can be attained given covariate history, then longitudinal causal methods can be applied to account for the HWSE. Past studies have applied causal methods capable of accounting for time-varying confounding affected by past exposure to the study of MWF exposures and cancer mortality outcomes in the UAW-GM Cohort Study [@Garcia_2018;@Izano_2019]. However, the study of cancer incidence outcomes is further problematized by the incomplete observation of cancer incidence outcomes at every point of follow-up over the study period. Nonetheless, we wish to make inferences about the carcinogenicity of MWF exposure over an individual's lifetime starting upon entry into the workforce. The UAW-GM Cohort included those hired roughly between 1938 and 1985. However, cancer incidence reporting did not begin until 1973. Hence, our observed cohort data exhibits _left filtering_: cancer incidence is the outcome of interest, but before 1985, both cancer incidence status and time of cancer incidence are unknown. Observation of the complete cancer incidence outcome vector over the study period was conditional on an individual surviving to 1985 cancer-free.

In the presence of the HWSE, left filtering implies outcome misclassification that is informative of true cancer status. As part of her dissertation research, @Izano_2017_thesis conducted a quantitative bias analysis for the estimation of survival curves using left filtered data in the presence of HWSE. She simulated data compatible with the HWSE and estimated cancer-free survival curves using an inverse probability of treatment and censoring weighted Kaplan-Meier (WKM) estimator and the WKM with an Aalen filter for left-filtering (AWKM) [@Andersen_1993;@Xie_2005]. Data were simulated under five different scenarios. The survival curves under the following interventions were computed or estimated in 250 replicates: (1) always exposed at work with no censoring due to death and (2) never exposed at work with no censoring due to death. For each intervention, three survival curves were produced: (1) the true survival curve, (2) the WKM survival curve, and (3) AWKM survival curve. Estimator bias was evaluated by comparing the average of 250 estimates of to the average difference in cancer-free survival under the two rules to the true average difference in survival when exposure and censoring were controlled deterministically.

The present project replicates the simulation and bias analyses presented in Chapter 3 of @Izano_2017_thesis, embeds the problem in the non-parametric structural causal approach of @Pearl_1995, and applies the WKM and AWKM estimators to the estimation of digestive-system cancer-free survival under exposure and no censoring rules in the UAW-GM Cohort. The `stremr` package was used to estimate the WKM and AWKM survival curves in both the simulation and the applied analyses [@Sofrygin_2021].