---
output:
  pdf_document:
    includes:
      in_header: "~/headRs/StatHead.sty"
fontsize: 11pt
bibliography: "../../causal.bib"
# csl: "`r path.expand('~/HeadRs/csl/ama.csl')`"
---

# Discussion

In the simulation study, we showed that the inverse probability of exposure/censoring weighted Kaplan-Meier estimator resulted in lower bias in the estimation of average survival time than did the weighted Kaplan-Meier estimator without the Aalen filter. While the Aalen filter corrects for non-informative left-filtering in the estimation of the discrete hazard by excluding person-years not observed under the cancer registry. These person-years contribute to estimation during the estimation of exposure and censoring weights. Speculatively, the combination of the two extensions to the Kaplan-Meier estimator may result in the partial control of informative left censoring without adjusting for informative left truncation.

The simulation permitted the evaluation of the estimators in clean, well-behaved scenarios, but the same luxury was not possible when using observed data. Several assumptions used in the simulation study were incompatible with what is known about cancer epidemiology. Firstly, cumulative incidence in the simulations was close to 15\% (or higher) over a 20-year follow-up. This is an extraordinarily high risk of cancer, especially because most workers in the automotive manufacturing industry start their careers at a fairly young age. Digestive system cancers are among the most common forms of cancer in the Unite states, and in 35 years of follow-up, we were still only able to observe a cumulative incidence of less than 1\%. The simulation scenarios suggest that the bias of the WKM and AWKM estimators is higher when cumulative incidence is higher, but when cumulative incidence is low, we rely on very few observations to index the risk sets.

There are multiple opportunities for future work. The simulation study can be expanded to investigate subtler exposure-outcome effects. In the present work, the discrete hazard ratio of cancer incidence given exposure was rather high at about 1.28. Furthermore, we assumed the luxury of knowing the true treatment and censoring mechanisms' model forms, but this is quite unrealistic. In future simulations, the effect of model mis-specification should be investigated. Alternatively, we could estimate survival using a doubly robust method. There can also be several improvements made from the subject-matter expertise point-of-view. The exposure rules investigated in the applied analysis were chosen naively. Other dynamic or stochastic exposure interventions may have been of greater interest to occupational health policy, and they may have led to improved numeric performance as well. The present analysis did not lag exposure status, which is standard practice in cancer epidemiology -- the biological responses to carcinogens do not occur until several years or decades after exposure. The true causal effects of MWF exposure may not yet be observable after 35 years of follow-up.